version: 2
updates:
- package-ecosystem: gradle
  directory: "/spring-boot-containers"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.1
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
