package com.softwarelabs;

import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
public class App {
	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}

	public String getGreeting() {
		return "Hello world.";
	}
}
