/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.softwarelabs;

import com.softwarelabs.config.IntegrationTestConfiguration;
import com.softwarelabs.product.ProductController;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
@Import(IntegrationTestConfiguration.class)
public class ApplicationContextTest {

    @Autowired
    private ProductController productController;

    @Test
    public void contextLoads() {
        assertNotNull(productController);
    }
}
