/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.softwarelabs;

import com.softwarelabs.product.ProductController;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
public class ApplicationContextTest {

	@Autowired private ProductController productController;

	@Test
	public void contextLoads() {
		assertNotNull(productController);
	}
}
