/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

	public static void main(String[] args) {
		new App().calculateSumParallel();
	}

	public int calculateSumParallel() {
		int[] input = {1, 2, 3, 4, 5};
		ArraySum arraySum = new ArraySum(0, 4, input);
		arraySum.compute();
		System.out.println("Sum:" + arraySum.sum);
		return arraySum.sum;
	}
}
