spring:
  application:
    name: api-throttling
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${ENV_KAFKA_BOOTSTRAP_SERVERS}
    consumer.group-id: ${spring.application.name}
    producer:
      acks: 'all'
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest