spring:
  port: 12345
  config:
    activate:
      on-profile: dev
  application:
    name: spring-boot-kafka
  datasource:
    driver-class-name: ${ENV_DRIVER_CLASS_NAME}
    url: ${ENV_DATASOURCE_URL}
    username: ${ENV_DATASOURCE_SERVICE_USERNAME}
    password: ${ENV_DATASOURCE_SERVICE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
---

spring:
  config:
    activate:
      on-profile: dev


ENV_DATASOURCE_URL: jdbc:postgresql://postgres/store
ENV_DATASOURCE_SERVICE_USERNAME: dbuser
ENV_DATASOURCE_SERVICE_PASSWORD: password
ENV_DRIVER_CLASS_NAME: org.postgresql.Driver
ENV_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
ENV_ZOOKEEPER_CONNECT_STRING: zookeeper:2181


---

spring:
  config:
    activate:
      on-profile: integration

