/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.softwarelabs;

import com.softwarelabs.kafka.BaseIntegrationTest;
import com.softwarelabs.product.ProductController;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertNotNull;


@SpringBootTest
public class ApplicationContextTest extends BaseIntegrationTest {

    @Autowired
    private ProductController productController;

    @Test
    public void contextLoads() {
        assertNotNull(productController);
    }
}
