server:
  port: ${ENV_APPLICATION_PORT}
spring:
  application:
    name: api-throttling
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${ENV_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: 'all'
    consumer:
      enable-auto-commit: false
      auto-offset-reset: latest
      group-id: ${ENV_KAFKA_CONSUMER_GROUP_ID}

product_order_service_base_url: ${ENV_PRODUCT_ORDER_SERVICE_URL}
