spring.profiles.active: dev

server.port: ${ENV_APPLICATION_PORT}

spring:
  application:
    name: spring-boot-kafka-cluster-consumer
  datasource:
    driver-class-name: ${ENV_DRIVER_CLASS_NAME}
    url: ${ENV_DATASOURCE_URL}
    username: ${ENV_DATASOURCE_SERVICE_USERNAME}
    password: ${ENV_DATASOURCE_SERVICE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  kafka:
    clientId: ${ENV_APPLICATION_CLIENTID}

---

spring.profiles: dev


ENV_DATASOURCE_URL: jdbc:postgresql://postgres/store
ENV_DATASOURCE_SERVICE_USERNAME: dbuser
ENV_DATASOURCE_SERVICE_PASSWORD: password
ENV_DRIVER_CLASS_NAME: org.postgresql.Driver

kafka:
  bootstrap:
    servers: ${ENV_KAFKA_BOOTSTRAP_SERVERS}
---

spring.profiles: integration
ENV_APPLICATION_PORT: 12345
